//
// FitnessCenterListResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

struct FitnessCenterListResponse: Codable {

    let id: String?
    let name: String?
    let address: String?
    let geoLocation: GeoLocation?

  enum CodingKeys: String, CodingKey {
        case id
        case name
        case address
        case geoLocation
    }

}
